PROMPT &&delimiter
PROMPT Script start: grants.sql
PROMPT &&delimiter

DEFINE SCHEMA_NAME = &&1

PROMPT &&delimiter
PROMPT Granting privileges to &&SCHEMA_NAME
PROMPT &&delimiter

GRANT CREATE PROCEDURE TO &SCHEMA_NAME;
GRANT CREATE SEQUENCE TO &SCHEMA_NAME;
GRANT CREATE TABLE TO &SCHEMA_NAME;
GRANT CREATE TYPE TO &SCHEMA_NAME;
GRANT CREATE TRIGGER TO &SCHEMA_NAME;
GRANT CREATE SYNONYM TO &SCHEMA_NAME;
GRANT CREATE SESSION TO &SCHEMA_NAME;
GRANT CREATE ANY DIRECTORY TO &SCHEMA_NAME;
GRANT CREATE TABLE TO &&SCHEMA_NAME;
GRANT CREATE ANY EDITION TO &&SCHEMA_NAME;
GRANT DROP ANY EDITION TO &&SCHEMA_NAME;
GRANT CREATE ANY VIEW TO &&SCHEMA_NAME;
GRANT ALTER DATABASE TO &&SCHEMA_NAME;

ALTER USER &&SCHEMA_NAME ENABLE EDITIONS;

GRANT READ ON DIRECTORY &SCHEMA_NAME._IMP TO &SCHEMA_NAME; 
GRANT WRITE ON DIRECTORY &SCHEMA_NAME._IMP TO &SCHEMA_NAME; 

UNDEFINE SCHEMA_NAME

PROMPT &&delimiter
PROMPT Script start: grants.sql
PROMPT &&delimiter


