DEFINE delimiter = '-------------------------------------------------------------'
DEFINE SCRIPT_NAME = 'create_ebr_tool_tables'

PROMPT &&delimiter
PROMPT Script start: &&SCRIPT_NAME
PROMPT &&delimiter

DEFINE;

CREATE TABLE ebr_tool_phase (
    id           INTEGER GENERATED BY DEFAULT  AS IDENTITY start with 1,
    phase_name   VARCHAR2(100) NOT NULL,
    last_update  DATE DEFAULT sysdate,
	start_date   DATE,
	end_date     DATE,
    status       VARCHAR2(100),
    description  VARCHAR2(200)
);

/

CREATE TABLE ebr_tool_table (
    id             INTEGER GENERATED BY DEFAULT  AS IDENTITY START WITH 1,
    table_name     VARCHAR2(100) NOT NULL,
    ebr_phase_id   INTEGER NOT NULL,
    new_table_name VARCHAR2(100) NOT NULL,
    view_name      VARCHAR2(100),
    phase_id       INTEGER NOT NULL,
    last_update    DATE DEFAULT sysdate,
    status         VARCHAR2(20),
    description    VARCHAR2(200)
);

/

ALTER TABLE ebr_tool_phase
    ADD CONSTRAINT pk_ebr_tool_phase_id
PRIMARY KEY (id);

/

ALTER TABLE ebr_tool_table
    ADD CONSTRAINT pk_ebr_tool_table_id
PRIMARY KEY (id);

/

ALTER TABLE ebr_tool_table
    ADD CONSTRAINT fk_ebr_tool_phase_ebr_tool_table_id
FOREIGN KEY (ebr_phase_id)
    REFERENCES ebr_tool_phase (id);

/

PROMPT &&delimiter
PROMPT Script end: &&SCRIPT_NAME
PROMPT &&delimiter
