REM Status ---> null, Table Renamed, View Created, Failed, In Progress, Completed

CREATE TABLE ebr_tool (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 NOT NULL,
    table_name     VARCHAR2(100) NOT NULL,
	new_table_name VARCHAR2(100) ,
    view_name      VARCHAR2(100) ,
    phase_num      INTEGER       ,
    phase_name     VARCHAR2(100) ,
    last_update    DATE NOT NULL default sysdate,
    status         VARCHAR2(50),
    description    VARCHAR2(2000)
);

INSERT INTO ebr_tool (table_name) VALUES ('PCMS_ISSUANCEENTRY_UPDATE');
INSERT INTO ebr_tool (table_name) VALUES ('CMS_STOCK_REPORT');
INSERT INTO ebr_tool (table_name) VALUES ('CMS_UPLOAD_CTRL');
INSERT INTO ebr_tool (table_name) VALUES ('CMS_UPLOAD_SUMMARY');
INSERT INTO ebr_tool (table_name) VALUES ('CMS_BRANCH_TRANSFER');
INSERT INTO ebr_tool (table_name) VALUES ('CMS_BULK_ACTIVITY_REPORT');