
CREATE TABLE EBR_LIST 
(
  TABLE_NAME VARCHAR2(100) 
);

INSERT INTO EBR_LIST (TABLE_NAME) VALUES ('PCMS_ISSUANCEENTRY_UPDATE');
INSERT INTO EBR_LIST (TABLE_NAME) VALUES ('CMS_STOCK_REPORT');
INSERT INTO EBR_LIST (TABLE_NAME) VALUES ('CMS_UPLOAD_CTRL');
INSERT INTO EBR_LIST (TABLE_NAME) VALUES ('CMS_UPLOAD_SUMMARY');
INSERT INTO EBR_LIST (TABLE_NAME) VALUES ('CMS_BRANCH_TRANSFER');
INSERT INTO EBR_LIST (TABLE_NAME) VALUES ('CMS_BULK_ACTIVITY_REPORT');


ID sequence
Table_name
View_name
Phase_num
Phase_name
Last_update
Status ---> null, Table Renamed, View Created, Failed, In Progress, Completed
Description